"""End-to-end scenario tests for the Document Processing Agent, run with
real generated files (real PDF bytes / real DOCX bytes) rather than mocked
extraction, plus their integration into the format the Risk/Policy agents
consume.

Covers the four required scenarios:
    1. English document (PDF)
    2. Arabic document (DOCX)
    3. Mixed Arabic/English document (DOCX)
    4. Scanned PDF requiring OCR (genuine image-only PDF, no text layer)

Arabic PDFs generated by fpdf2 (no bidi/shaping engine) come back from
pypdf with each RTL run's character order reversed - a known artifact of
naive PDF authoring, not something app.tools.language_detection or
document_extract can or should compensate for. detect_language() is
order-independent (it just counts script membership) so it isn't
affected, but substring-based document_type keyword matching would be, so
scenarios 2 and 3 use DOCX (Word XML stores Unicode in logical reading
order) to get a clean, representative round trip. Scenario 1 (English) and
4 (image-only scanned PDF) are unaffected by this and use real PDFs.

Run with: pytest tests/test_document_agent_scenarios.py -v -s
(the -s is needed to see the printed per-scenario report)
"""
import re
from io import BytesIO

import img2pdf
import pytest
from docx import Document
from fpdf import FPDF
from PIL import Image, ImageDraw, ImageFont

from app.agents.document_agent import DocumentProcessingAgent
from app.models import DocumentLanguage
from app.tools import ocr as ocr_module

FONT_PATH = "C:/Windows/Fonts/segoeui.ttf"


def _arabic(*codepoints: int) -> str:
    return "".join(chr(cp) for cp in codepoints)


ARABIC_SENTENCE = _arabic(
    # "hathihi siyasat al-khususiya lil-sharika. nahnu naltazim bi-himayat
    #  bayanat al-umala." (This is the company's privacy policy. We are
    #  committed to protecting customer data.)
    0x0647, 0x0630, 0x0647, 0x0020, 0x0633, 0x064A, 0x0627, 0x0633, 0x0629, 0x0020,
    0x0627, 0x0644, 0x062E, 0x0635, 0x0648, 0x0635, 0x064A, 0x0629, 0x0020,
    0x0644, 0x0644, 0x0634, 0x0631, 0x0643, 0x0629, 0x002E, 0x0020,
    0x0646, 0x0644, 0x062A, 0x0632, 0x0645, 0x0020,
    0x0628, 0x062D, 0x0645, 0x0627, 0x064A, 0x0629, 0x0020,
    0x0628, 0x064A, 0x0627, 0x0646, 0x0627, 0x062A, 0x0020,
    0x0627, 0x0644, 0x0639, 0x0645, 0x0644, 0x0627, 0x0621, 0x002E,
)

ENGLISH_PAGE_1 = (
    "Vendor Risk Assessment Report\n\n"
    "This document evaluates a third-party AI vendor's customer support "
    "system. The system processes customer email addresses and phone "
    "numbers to triage support tickets automatically."
)
ENGLISH_PAGE_2 = (
    "The vendor has confirmed SOC 2 Type II compliance and provides a "
    "human review step for any escalation the model flags as high risk."
)

SCANNED_IMAGE_TEXT = "This is a scanned document. OCR is required to extract this text."


def _report(scenario, result, passed, notes=""):
    print(f"\n{'=' * 70}")
    print(f"SCENARIO: {scenario}")
    print(f"{'=' * 70}")
    print(f"file_name        : {result.file_name}")
    print(f"file_type        : {result.file_type}")
    print(f"detected_language: {result.detected_language.value}")
    print(f"page_count       : {result.page_count}")
    print(f"ocr_used         : {result.ocr_used}")
    print(f"document_type    : {result.document_type}")
    print(f"word_count       : {result.word_count}")
    print(f"warnings         : {result.warnings or '(none)'}")
    print(f"extracted_text   :\n{result.extracted_text!r}")
    print(f"{'-' * 70}")
    print(f"RESULT: {'PASS' if passed else 'FAIL'}" + (f" - {notes}" if notes else ""))


# =========================================================
# Scenario 1: English document (PDF)
# =========================================================


def test_scenario_1_english_pdf():
    pdf = FPDF()
    pdf.add_page()
    pdf.add_font("Segoe", "", FONT_PATH)
    pdf.set_font("Segoe", size=12)
    pdf.multi_cell(190, 8, ENGLISH_PAGE_1)
    pdf.add_page()
    pdf.set_font("Segoe", size=12)
    pdf.multi_cell(190, 8, ENGLISH_PAGE_2)
    content = bytes(pdf.output())

    result = DocumentProcessingAgent().process("vendor_risk_assessment.pdf", content)

    # fpdf2's justified multi_cell() stretches lines to full width by
    # inserting extra spaces between words (pypdf's extraction faithfully
    # preserves that PDF-layer detail) - collapse whitespace runs before
    # substring checks so the test verifies *content*, not exact spacing.
    normalized_text = re.sub(r"\s+", " ", result.extracted_text)

    checks = {
        "file_type == pdf": result.file_type == "pdf",
        "detected_language == english": result.detected_language == DocumentLanguage.ENGLISH,
        "page_count == 2": result.page_count == 2,
        "ocr_used is False": result.ocr_used is False,
        "document_type == risk_assessment": result.document_type == "risk_assessment",
        "text contains page 1 content": "Vendor Risk Assessment" in normalized_text,
        "text contains page 2 content": "SOC 2" in normalized_text,
    }
    passed = all(checks.values())
    failed = [k for k, v in checks.items() if not v]
    _report("1. English document (PDF)", result, passed, notes="; ".join(failed))

    for check_name, ok in checks.items():
        assert ok, check_name


# =========================================================
# Scenario 2: Arabic document (DOCX)
# =========================================================


def test_scenario_2_arabic_docx():
    doc = Document()
    doc.add_paragraph(ARABIC_SENTENCE)
    buf = BytesIO()
    doc.save(buf)
    content = buf.getvalue()

    result = DocumentProcessingAgent().process("privacy_policy_ar.docx", content)

    checks = {
        "file_type == docx": result.file_type == "docx",
        "detected_language == arabic": result.detected_language == DocumentLanguage.ARABIC,
        "ocr_used is False": result.ocr_used is False,
        "document_type == privacy_policy": result.document_type == "privacy_policy",
        "extracted text matches source exactly": ARABIC_SENTENCE in result.extracted_text,
    }
    passed = all(checks.values())
    failed = [k for k, v in checks.items() if not v]
    _report("2. Arabic document (DOCX)", result, passed, notes="; ".join(failed))

    for check_name, ok in checks.items():
        assert ok, check_name


# =========================================================
# Scenario 3: Mixed Arabic/English document (DOCX)
# =========================================================


def test_scenario_3_mixed_docx():
    doc = Document()
    doc.add_paragraph("Privacy Policy / Bilingual Notice")
    doc.add_paragraph(
        "This company processes customer data in accordance with applicable law."
    )
    doc.add_paragraph(ARABIC_SENTENCE)
    buf = BytesIO()
    doc.save(buf)
    content = buf.getvalue()

    result = DocumentProcessingAgent().process("bilingual_notice.docx", content)

    checks = {
        "file_type == docx": result.file_type == "docx",
        "detected_language == mixed": result.detected_language == DocumentLanguage.MIXED,
        "ocr_used is False": result.ocr_used is False,
        "document_type == privacy_policy": result.document_type == "privacy_policy",
        "text contains English paragraph": "processes customer data" in result.extracted_text,
        "text contains Arabic paragraph": ARABIC_SENTENCE in result.extracted_text,
    }
    passed = all(checks.values())
    failed = [k for k, v in checks.items() if not v]
    _report("3. Mixed Arabic/English document (DOCX)", result, passed, notes="; ".join(failed))

    for check_name, ok in checks.items():
        assert ok, check_name


# =========================================================
# Scenario 4a: Scanned PDF requiring OCR - REAL environment
# (no tesseract/poppler binaries installed here -> must degrade gracefully)
# =========================================================


def _make_scanned_pdf() -> bytes:
    image = Image.new("RGB", (900, 300), color="white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(FONT_PATH, 28)
    draw.text((20, 120), SCANNED_IMAGE_TEXT, fill="black", font=font)
    img_buf = BytesIO()
    image.save(img_buf, format="PNG")
    return img2pdf.convert(img_buf.getvalue())


def test_scenario_4a_scanned_pdf_real_environment():
    content = _make_scanned_pdf()
    ocr_available = ocr_module.is_ocr_available()

    result = DocumentProcessingAgent().process("scanned_notice.pdf", content)

    checks = {
        "file_type == pdf": result.file_type == "pdf",
        "page_count == 1": result.page_count == 1,
        "pypdf text layer is empty (genuinely image-only)": result.word_count == 0
        or not ocr_available,
        "warnings explain missing text": bool(result.warnings),
    }
    passed = all(checks.values())
    failed = [k for k, v in checks.items() if not v]
    notes = "; ".join(failed)
    if not ocr_available:
        notes = (notes + "; " if notes else "") + (
            "NOTE: tesseract-ocr binary is not installed in this environment "
            "(requires admin rights to install) - OCR fallback correctly "
            "detected as unavailable and degraded gracefully instead of "
            "crashing. See test_scenario_4b for the OCR-available code path."
        )
    _report(
        f"4a. Scanned PDF requiring OCR (real environment, ocr_available={ocr_available})",
        result,
        passed,
        notes=notes,
    )

    for check_name, ok in checks.items():
        assert ok, check_name


# =========================================================
# Scenario 4b: Scanned PDF requiring OCR - SIMULATED OCR engine
# Proves the agent's OCR wiring/logic works correctly, using a monkeypatch
# to stand in for the tesseract binary this machine doesn't have installed.
# =========================================================


def test_scenario_4b_scanned_pdf_with_ocr_simulated(monkeypatch):
    content = _make_scanned_pdf()

    def fake_ocr_pdf(pdf_bytes, languages=ocr_module.DEFAULT_OCR_LANGUAGES):
        return SCANNED_IMAGE_TEXT, True

    monkeypatch.setattr("app.tools.document_extract.ocr_pdf", fake_ocr_pdf)

    result = DocumentProcessingAgent().process("scanned_notice.pdf", content)

    checks = {
        "file_type == pdf": result.file_type == "pdf",
        "page_count == 1": result.page_count == 1,
        "ocr_used is True": result.ocr_used is True,
        "detected_language == english": result.detected_language == DocumentLanguage.ENGLISH,
        "extracted_text == simulated OCR output": result.extracted_text == SCANNED_IMAGE_TEXT,
        "warnings mention OCR recovery": any("OCR" in w for w in result.warnings),
    }
    passed = all(checks.values())
    failed = [k for k, v in checks.items() if not v]
    _report(
        "4b. Scanned PDF requiring OCR (SIMULATED tesseract via monkeypatch)",
        result,
        passed,
        notes="; ".join(failed) or "SIMULATED - not a real tesseract OCR run",
    )

    for check_name, ok in checks.items():
        assert ok, check_name
